### PR TITLE
Feature events

### PR DESCRIPTION
**Pull request by AlejandroNo4**
This project was made for learning proposes, to implement ActiveRecord’s associations using Ruby On Rails, so users can create events as well as assist them.

### CODE REVIEW

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @AlejandroNo4  :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this milestone can be approved.

## REQUIRED

* [x] Your README title says **`BASIC FORMS RAILS`**. Kindly change that
* [x] Webpacker is needed to run your project. Kindly add that to the **`Setup and Usage`** section of your README
* [x] `Event's index` page should display past and upcoming events lists. You currently do not have the event's index page
* [x] You have the code for the `event's show` page but there's no link to it on your page
* [x] The `user's show` page should display events the user has created and events that the user is attending, separated in past and upcoming. The `user's show` page currently displays the created events but does not separate the events into past and upcoming.





## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by AlejandroNo4** [comment]
Hello! the Users page shows all created, future, and past events, but you have to be logged in or create your own account to see them. 

Captura de Pantalla 2021-04-12 a la(s) 14 32 09

The link to the "Show event" it's actually the "See attendees" button. It will redirect to the event's show page showing also the attendees.

**Comment by AlejandroNo4** [comment]
Also changed the index events to be the root. Now the events are divided into past and upcoming.

Captura de Pantalla 2021-04-12 a la(s) 15 19 49

**Review by cyonii — APPROVED** [review]
### STATUS: APPROVED 🎉✅

Thank you for implementing all the requested changes, your project has now meet the full requirements, you can merge this PR and move on. 

#### NICE TO HAVE
Note that these are optional suggestions to improve your project. As they're not mandatory, you are not obliged to implement them.

- [ ] Your app breaks when I try to log out, this is not good for UX.
- [ ] Your event delete feature is not functional, please fix this.

> #### <br>You can ping me on Slack @[CY Kalu](https://microverse-students.slack.com/team/U01494U96FR) to draw my attention in case I do not respond quickly on here. I'm always available and will be glad to help.<br><br>

**Pull request merged**
